version: '3.7'

services:
  rancher:
    image: rancher/rancher:latest
    container_name: rancher
    restart: unless-stopped
    ports:
      - "8443:443"  # Porta para acessar a interface via HTTPS
      - "880:80"    # Porta para redirecionamento HTTP, se necessário
    environment:
      CATTLE_SERVER_URL: "https://192.168.15.3:8443" # URL do Rancher para comunicação com agentes
      CATTLE_AGENT_CONNECT: "true"  # Permite que os agentes se conectem
    volumes:
      - rancher-data:/var/lib/rancher  # Persistência de dados
    networks:
      default:
        ipv4_address: 10.21.0.40  # IP fixo na sub-rede Docker

volumes:
  rancher-data:

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 10.21.0.0  # Sub-rede usada pelo Docker
