version: '3.7'

services:
  app_proxy:
    container_name: rancher_app_proxy_1
    environment:
      APP_HOST: rancher_nginx_1     # <<< agora aponta para o nginx, e não direto para o Rancher
      APP_PORT: 80                  # <<< nginx vai responder em HTTP
      APP_HTTPS: 'false'             # <<< fala HTTP interno com o nginx
      PROXY_PORT: 8443               # <<< porta externa como você queria
      PROXY_AUTH_ADD: 'false'
    networks:
      - umbrel_main_network

  rancher_nginx:
    image: nginx:latest
    container_name: rancher_nginx_1
    restart: unless-stopped
    networks:
      - umbrel_main_network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # vamos criar esse arquivo nginx.conf

  rancher:
    image: rancher/rancher:latest
    container_name: rancher_server_1
    hostname: rkgi.servehttp.com
    privileged: true
    restart: unless-stopped
    init: true
    environment:
      TZ: America/Sao_Paulo
      CATTLE_SERVER_URL: "https://rkgi.servehttp.com:8443"
      CATTLE_AGENT_CONNECT: "true"
    volumes:
      - ${APP_DATA_DIR}/data/rancher:/var/lib/rancher
    networks:
      umbrel_main_network:
        ipv4_address: 10.21.0.40

networks:
  umbrel_main_network:
    external: true
