version: '3.7'

services:
  rancher:
    image: rancher/rancher:latest
    container_name: my-umbrel-rancher_1
    hostname: "${RANCHER_HOSTNAME}"
    privileged: true
    restart: unless-stopped
    init: true
    ports:
      - "880:80" # Porta para acesso HTTP
      - "8443:443" # Porta para acesso HTTPS (se configurado manualmente)
    volumes:
      - ${APP_DATA_DIR}/data/rancher:/var/lib/rancher
    environment:
      TZ: America/Sao_Paulo
    networks:
      umbrel_main_network:
        ipv4_address: 10.21.0.40

networks:
  umbrel_main_network:
    external: true
