services:
  app_proxy:
    container_name: rancher_app_proxy_1
    environment:
      APP_HOST: rancher_server_1
      APP_PORT: 80
      APP_HTTPS: 'false'
      PROXY_PORT: 8443
      PROXY_AUTH_ADD: 'false'
#    ports:
#      - "8443:443"  # Aqui está a mágica!

  rancher:
    image: rancher/rancher:latest
    container_name: rancher_server_1
    hostname: rkgi.servehttp.com
    privileged: true
    restart: unless-stopped
    init: true
    environment:
      TZ: America/Sao_Paulo
      CATTLE_SERVER_URL: "https://rkgi.servehttp.com:8443"
      CATTLE_AGENT_CONNECT: "true"
    volumes:
      - ${APP_DATA_DIR}/data/rancher:/var/lib/rancher
    networks:
      umbrel_main_network:
        ipv4_address: 10.21.0.40

networks:
  umbrel_main_network:
    external: true
