version: '3.7'

services:
  app_proxy:
    container_name: rancher_app_proxy_1
    environment:
      APP_HOST: rancher_server_1
      APP_PORT: 443
      PROXY_AUTH_ADD: 'false'
    image: getumbrel/nginx-proxy-manager
    restart: unless-stopped
    networks:
      - umbrel_main_network

  rancher_server_1:
    image: rancher/rancher:latest
    container_name: rancher_server_1
    hostname: ${DEVICE_HOSTNAME:-rkgi.servehttp.com}
    privileged: true
    restart: unless-stopped
    init: true
    environment:
      TZ: America/Sao_Paulo
    volumes:
      - ${APP_DATA_DIR}/data/rancher:/var/lib/rancher
    ports:
      - "8443:443"  # expõe diretamente a interface via :8443, como no seu domínio
    networks:
      umbrel_main_network:
        ipv4_address: 10.21.0.40

networks:
  umbrel_main_network:
    external: true
