version: '3.7'

services:
  app_proxy:
    container_name: rancher_app_proxy_1
    environment:
      APP_HOST: rancher_server_1         # Nome do serviço abaixo
      APP_PORT: 443                      # Porta interna do Rancher (HTTPS)
      PROXY_AUTH_ADD: 'false'
    # Não precisa de image, pois o Umbrel ou NPM injeta isso dinamicamente

  rancher:
    image: rancher/rancher:latest
    container_name: rancher_server_1
    hostname: "${RANCHER_HOSTNAME:-rkgi.servehttp.com}"
    privileged: true
    restart: unless-stopped
    init: true

    # As portas não precisam ser mapeadas se o proxy estiver ativo
    # ports:
    #   - "8443:443"
    #   - "880:80"

    environment:
      TZ: America/Sao_Paulo
      CATTLE_SERVER_URL: "https://rkgi.servehttp.com"
      CATTLE_AGENT_CONNECT: "true"

    volumes:
      - ${APP_DATA_DIR}/data/rancher:/var/lib/rancher

    networks:
      umbrel_main_network:
        ipv4_address: 10.21.0.40

networks:
  umbrel_main_network:
    external: true
