version: '3.7'

services:
  rancher:
    image: rancher/rancher:v2.11.0@sha256:67e8e220bf08388709720a08af19e28d7a61085130f7976381ea2800faa24159
    hostname: "${DEVICE_HOSTNAME}"
    privileged: true
    restart: unless-stopped
    init: true
    ports:
      - "880:80"
      - "8443:443"
    volumes:
      - ${APP_DATA_DIR}/data/rancher:/var/lib/rancher
    environment:
      TZ: America/Sao_Paulo
      CATTLE_SERVER_URL: "https://100.70.0.0:8443"
      CATTLE_AGENT_CONNECT: "true"
    networks:
      umbrel_main_network:
        ipv4_address: 10.21.0.40

 password-updater:
    image: alpine:3.18
    container_name: rancher_password_updater
    depends_on:
      - rancher
    volumes:
      - ${APP_DATA_DIR}/data/rancher:/var/lib/rancher
      - ${APP_DATA_DIR}/data:/data
    entrypoint: >
      sh -c "
      while [ ! -f /var/lib/rancher/bootstrap-password ]; do
        echo 'Aguardando a geracao da senha pelo Rancher...';
        sleep 5;
      done;
      echo 'Senha encontrada. Copiando para /data/rancher-password.txt...';
      cp /var/lib/rancher/bootstrap-password /data/rancher-password.txt;
      chmod 644 /data/rancher-password.txt;
      echo 'Senha salva com sucesso.'"
    restart: on-failure
    networks:
      - umbrel_main_network

networks:
  umbrel_main_network:
    external: true
