version: '3.7'

services:
  rancher:
    image: rancher/rancher:latest
    container_name: rancher_server_1
    hostname: rkgi.servehttp.com
    privileged: true
    restart: unless-stopped
    init: true
    ports:
      - "8443:443"
    environment:
      TZ: America/Sao_Paulo
      CATTLE_SERVER_URL: "https://rkgi.servehttp.com"
      CATTLE_AGENT_CONNECT: "true"
    volumes:
      - ${APP_DATA_DIR}/data/rancher:/var/lib/rancher
    networks:
      umbrel_main_network:
        ipv4_address: 10.21.0.40

networks:
  umbrel_main_network:
    external: true
